language: elixir
sudo: false
elixir: 1.6.1
otp_release: 20.1
matrix:
  include:
    - elixir: 1.3.0
      otp_release: 18.1
script:
  - if [[ `elixir -v` = *"1.6"* ]]; then mix format --check-formatted; fi
  - mix test
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
